export interface Project {
  title: string;
  desc: string;
  source?: string;
  url?: string;
  tech: string[];
  company?: string;
  client?: string;
  date: string;
  featured?: boolean;
}

export const projects: Project[] = [
  {
    title: 'AI-Powered Care Platforms',
    desc: 'Contributed to two AI-powered platforms at A Place for Mom: a B2C care-finder helping families locate senior care facilities, and a B2B outreach tool connecting home care agencies with care-seekers via AI-driven speech/text pipelines and Twilio voice conferencing. Both shipped from prototype to production in under three months.',
    url: 'https://findcare.aplaceformom.com/',
    tech: [
      'Next.js',
      'React',
      'TypeScript',
      'Storybook',
      'Tailwind',
      'Twilio',
      'PostHog',
      'Jest',
    ],
    company: 'A Place for Mom',
    date: '2025/01/01',
    featured: true,
  },
  {
    title: 'A Place for Mom',
    desc: 'Contributed to frontend development of aplaceformom.com, a high-traffic Next.js platform helping families search for senior care and retirement facilities. Work focused on SEO optimization, performance, reliability, and migrating from legacy systems to a unified modern stack.',
    url: 'https://www.aplaceformom.com/',
    tech: [
      'Next.js',
      'React',
      'TypeScript',
      'Storybook',
      'Tailwind',
      'AWS',
      'Cloudinary',
    ],
    company: 'A Place for Mom',
    date: '2022/08/01',
    featured: true,
  },
  {
    title: 'OpenSea Integration',
    desc: 'ReactJS + Web3 integration for viewing and buying NFTs from OpenSea directly in OctoFi app.',
    source: 'https://github.com/OctoFi/octofi-app-aquafarm',
    tech: ['React', 'Redux', 'Web3'],
    company: 'Freelance',
    client: 'OctoFi',
    date: '2020/10/12',
    featured: false,
  },
  {
    title: 'Jekyll Theme',
    desc: 'Clean minimalist theme for Jekyll using TailwindCSS.',
    source: 'https://github.com/nathanjessen/blogtheme',
    url: 'https://nathanjessen.github.io/blogtheme/',
    tech: ['Jekyll', 'TailwindCSS'],
    company: 'Freelance',
    date: '2022/07/18',
  },
  {
    title: 'Checking Account Recommender',
    desc: 'Find the best checking account for you using this questionnaire app.',
    url: 'https://www.firsthorizon.com/Products-and-Services/Banking/Checking-Accounts/Checking-Account-Recommender',
    tech: ['Vue'],
    company: 'VML',
    client: 'First Horizon Bank',
    date: '2019/07/01',
  },
  {
    title: 'Estimāte',
    desc: 'An internal tool for estimating the cost of a project proposal.',
    tech: ['AngularJS', 'Sass', 'Gulp'],
    company: 'VML',
    client: 'VMLY&R',
    date: '2018/10/01',
  },
  {
    title: 'Resource Allocation and Forecasting Tool',
    desc: 'An internal tool for allocating team members to upcoming/current projects.',
    tech: ['Vue', 'Ember', 'PHP'],
    company: 'VML',
    client: 'VMLY&R',
    date: '2018/10/01',
  },
  {
    title: 'Bridgestone Dealer Portal',
    desc: 'Updates to a previous site built in AEM.',
    tech: ['AEM'],
    company: 'VML',
    client: 'Bridgestone',
    date: '2017/03/01',
  },
  {
    title: 'Sprint',
    desc: 'Complete website redesign including marketplace, shopping cart, and customer support.',
    tech: ['AEM', 'AngularJS', 'Sass', 'Gulp', 'Sketch'],
    company: 'VML',
    client: 'Sprint',
    date: '2015/01/07',
  },
  {
    title: 'JG Wentworth',
    desc: 'Development of new page layouts and content banners.',
    tech: ['HTML', 'CSS'],
    company: 'VML',
    client: 'JG Wentworth',
    date: '2014/11/01',
  },
  {
    title: 'Mastercard',
    desc: 'Development of informational banners and page heros.',
    tech: ['HTML', 'CSS'],
    company: 'VML',
    client: 'Mastercard',
    date: '2014/09/01',
  },
  {
    title: 'PepsiCo Careers',
    desc: 'Fixed bugs and created new layout components for an existing careers portal.',
    url: 'https://www.pepsicojobs.com/main/',
    tech: ['HTML', 'CSS'],
    company: 'VML',
    client: 'PepsiCo',
    date: '2014/08/01',
  },
  {
    title: 'Efficacy',
    desc: 'Promotional landing page for the Sweat It. Get It. ad campaign.',
    tech: ['Jade', 'Stylus', 'Backbone', 'Grunt'],
    company: 'VML',
    client: 'Gatorade',
    date: '2014/07/30',
  },
  {
    title: 'League of Captains',
    desc: 'App with a comic book explorer interface for exploring the information of a marketing campaign.',
    tech: ['Jade', 'Stylus', 'Backbone', 'Grunt'],
    company: 'VML',
    client: 'Gatorade',
    date: '2014/07/21',
  },
  {
    title: 'Nonstop Love',
    desc: 'Landing page for a series of flight discount promotions.',
    tech: ['Assemble', 'Sass', 'Grunt'],
    company: 'VML',
    client: 'Southwest Airlines',
    date: '2014/06/14',
  },
  {
    title: 'UltraDuramune',
    desc: 'Created a CSS theme for an AEM website.',
    tech: ['AEM', 'Handlebars', 'Sass', 'Grunt'],
    company: 'VML',
    client: 'Boehringer Ingelheim',
    date: '2014/05/02',
  },
  {
    title: 'Edward Jones Careers',
    desc: 'Developed the initial prototype for a careers portal.',
    url: 'https://careers.edwardjones.com/',
    tech: ['HTML', 'CSS', 'JavaScript'],
    company: 'VML',
    client: 'Edward Jones',
    date: '2014/05/01',
  },
  {
    title: 'Taxonomy',
    desc: 'Internal informational website built in AEM.',
    tech: ['AEM', 'CSS'],
    company: 'VML',
    client: 'American Century Investments',
    date: '2014/02/01',
  },
  {
    title: 'Dollars and Sense',
    desc: 'Landing page for a new veterinary product.',
    tech: ['HTML5', 'Grunt', 'Sass'],
    company: 'VML',
    client: 'Boehringer Ingelheim',
    date: '2014/02/12',
  },
  {
    title: 'COO / Dealer Portal',
    desc: 'Internal portals for Bridgestone managers and product dealers.',
    tech: ['AEM', 'LESS', 'JavaScript'],
    company: 'VML',
    client: 'Bridgestone & Firestone',
    date: '2014/01/01',
  },
  {
    title: 'GCR/TDS Tires & Service',
    desc: 'Developed AEM components for a custom map with search for locating nearby stores.',
    tech: ['AEM', 'Handlebars', 'LESS', 'JavaScript'],
    company: 'VML',
    client: 'Bridgestone & Firestone',
    date: '2013/12/01',
  },
  {
    title: 'Have We Seen Your Cat Lately?',
    desc: 'Created a CSS theme for an AEM website.',
    tech: ['AEM', 'CSS', 'Gulp', 'Photoshop'],
    company: 'VML',
    client: 'Boehringer Ingelheim',
    date: '2013/11/10',
  },
  {
    title: 'Target Date',
    desc: 'Parallax website discussing a new program and its benefits.',
    tech: ['AEM', 'CSS', 'JavaScript', 'Photoshop'],
    company: 'VML',
    client: 'American Century Investments',
    date: '2013/05/01',
  },
  {
    title: 'ProZinc',
    desc: 'Created a CSS theme for an AEM website.',
    tech: ['AEM', 'Handlebars', 'Sass', 'Photoshop'],
    company: 'VML',
    client: 'Boehringer Ingelheim',
    date: '2013/04/11',
  },
  {
    title: 'Promotional Landing Page',
    desc: 'Built a landing page for a marketing campaign.',
    tech: ['HTML', 'CSS', 'Photoshop'],
    company: 'VML',
    client: 'Schrader',
    date: '2013/04/01',
  },
  {
    title: 'Duramune Lepto',
    desc: 'Created a custom video player for informational videos managed in AEM.',
    tech: ['AEM', 'JavaScript', 'Bootstrap'],
    company: 'VML',
    client: 'Boehringer Ingelheim',
    date: '2013/03/20',
  },
  {
    title: 'Rosedale Development Association',
    desc: 'Moved a community organization website into WordPress with a child theme at a Coders 4 Charities event.',
    url: 'https://rosedale.org/',
    tech: ['WordPress', 'CSS'],
    company: 'Volunteer',
    client: 'Rosedale Development Association',
    date: '2013/03/14',
  },
  {
    title: 'CardioDVM',
    desc: 'CSS updates and maintenance for an existing AEM website.',
    tech: ['AEM', 'CSS'],
    company: 'VML',
    client: 'Boehringer Ingelheim',
    date: '2013/03/01',
  },
  {
    title: 'Email Templates',
    desc: 'Built email templates used in a marketing campaign for tax preparation services and discounts.',
    tech: ['HTML', 'CSS'],
    company: 'VML',
    client: 'H&R Block',
    date: '2013/01/01',
  },
  {
    title: 'eVent Fabrics',
    desc: 'Developed a WordPress child theme for an apparel company.',
    // url: "http://eventfabrics.com",
    tech: ['WordPress', 'Photoshop'],
    company: 'VML',
    client: 'GE',
    date: '2013/01/15',
  },
  {
    title: 'ClearCurrent Pro',
    desc: 'HTML landing page with a custom YouTube video player.',
    // url: "http://www.clearcurrentpro.com"
    tech: ['HTML', 'CSS', 'JavaScript', 'Photoshop'],
    company: 'VML',
    client: 'GE',
    date: '2012/11/15',
  },
  {
    title: 'Pexion - Epilepsy in Dogs',
    desc: 'Responsive redesign of an AEM website.',
    // url: "https://www.pexion.co.uk/"
    tech: ['AEM', 'CSS', 'Photoshop'],
    company: 'VML',
    client: 'Boehringer Ingelheim',
    date: '2012/10/01',
  },
  {
    title: 'Purefil<sup>TM</sup> Technology',
    desc: 'Created a responsive CSS theme for an AEM website.',
    // url: "http://www.bivipurefil.com",
    tech: ['AEM', 'CSS', 'Photoshop'],
    company: 'VML',
    client: 'Boehringer Ingelheim',
    date: '2012/09/21',
  },
  {
    title: 'Email Templates',
    desc: 'Built email templates for an email marketing campaign.',
    tech: ['HTML', 'CSS'],
    company: 'VML',
    client: 'GE',
    date: '2012/09/01',
  },
  {
    title: 'LymeInfo',
    desc: 'Updated the CSS and content for an AEM website.',
    // url: "http://www.lymeinfo.com"
    tech: ['AEM', 'CSS'],
    company: 'VML',
    client: 'Boehringer Ingelheim',
    date: '2012/09/01',
  },
  {
    title: 'Pioneer Military Loans',
    desc: 'Fixed layout bugs and created CSS updates for a WordPress website.',
    url: 'https://pioneermilitarycredit.com/military-loans/',
    tech: ['WordPress', 'CSS'],
    company: 'VML',
    client: 'Pioneer Military Credit',
    date: '2012/09/01',
  },
  {
    title: 'Heartland Trailways',
    desc: 'Setup a WordPress site and created a child theme for a charter bus company.',
    // url: "http://www.heartlandtrailways.com"
    tech: ['WordPress', 'PHP', 'CSS', 'JavaScript'],
    company: 'Freelance',
    client: 'Heartland Trailways',
    date: '2011/10/07',
  },
  {
    title: 'Knacktive',
    desc: 'Developed the inaugural website for our university-led marketing agency and ported into the university CMS.',
    source: 'https://github.com/nathanjessen/knacktive',
    url: 'https://nathanjessen.github.io/knacktive/',
    tech: ['HTML', 'CSS', 'jQuery', 'Dreamweaver'],
    company: 'Northwest Missouri State University',
    client: 'Knacktive',
    date: '2011/02/01',
  },
];
