export interface Project {
  title: string;
  desc: string;
  img?: string;
  source?: string;
  url?: string;
  docs?: string;
  tech: string[];
  company?: string;
  client?: string;
  date: string;
  dateRange?: string[];
  archived?: boolean;
  featured?: boolean;
  published?: boolean;
}

export const projects: Project[] = [
  {
    title: "Storybook Component Library",
    img: "/assets/images/storybook-hodo.png",
    desc: "React components for an NFT marketplace were built in isolation using Storybook.",
    source: "https://github.com/Hodo-Network/hodo-network/tree/main/frontend",
    docs: "https://hodo-network.github.io/storybook-static/",
    tech: ["React", "Storybook", "Web3"],
    company: "Freelance",
    client: "Hodo Network",
    date: "2021/01/20",
    archived: false,
    featured: true,
  },
  {
    title: "Wordle",
    img: "/assets/images/wordle.png",
    desc: "Word game recreated with React.",
    source: "https://github.com/nathanjessen/wordle",
    url: "https://wordle.nathanjessen.com",
    docs: "https://nathanjessen.github.io/wordle",
    tech: ["React"],
    company: "Freelance",
    date: "2022/07/04",
    archived: false,
    featured: true,
  },
  {
    title: "OpenSea Integration",
    img: "/assets/images/opensea.png",
    desc: "ReactJS + Web3 integration for viewing and buying NFTs from OpenSea directly in OctoFi app.",
    source: "https://github.com/OctoFi/octofi-app-aquafarm",
    url: "https://app.octo.fi/",
    tech: ["React", "Redux", "Web3"],
    company: "Freelance",
    client: "OctoFi",
    date: "2020/10/12",
    dateRange: ["2020/02/01", "2021/12/15"],
    archived: false,
    featured: true,
  },
  {
    title: "Jekyll Theme",
    img: "/assets/images/blogtheme.png",
    desc: "Clean minimalist theme for Jekyll using TailwindCSS.",
    source: "https://github.com/nathanjessen/blogtheme",
    url: "https://nathanjessen.github.io/blogtheme/",
    tech: ["Jekyll", "TailwindCSS"],
    company: "Freelance",
    date: "2022/07/18",
    archived: true,
  },
  {
    title: "Uniswap Tokenlist",
    img: "/assets/images/tokenlist.png",
    desc: "Create an ERC20 token list and validate the JSON schema to display tokens in well-known UI's like Uniswap.",
    source: "https://github.com/nathanjessen/tokenlist-template",
    url: "https://github.com/nathanjessen/tokenlist-template",
    tech: ["JSON", "Ajv"],
    company: "Freelance",
    date: "2020/09/26",
    archived: true,
  },
  {
    title: "Checking Account Recommender",
    desc: "Find the best checking account for you using this questionnaire app.",
    url: "https://www.firsthorizon.com/Products-and-Services/Banking/Checking-Accounts/Checking-Account-Recommender",
    tech: ["Vue"],
    company: "VML",
    client: "First Horizon Bank",
    date: "2019/07/01",
    dateRange: ["2019/07/01", "2019/09/01"],
    archived: true,
  },
  {
    title: "Estimāte",
    desc: "An internal tool for estimating the cost of a project proposal.",
    tech: ["AngularJS", "Sass", "Gulp"],
    company: "VML",
    client: "VMLY&R",
    date: "2018/10/01",
    dateRange: ["Feb 2018", "July 2019"],
    archived: true,
  },
  {
    title: "Resource Allocation and Forecasting Tool",
    desc: "An internal tool for allocating team members to upcoming/current projects.",
    tech: ["Vue", "Ember", "PHP"],
    company: "VML",
    client: "VMLY&R",
    date: "2018/10/01",
    dateRange: ["Feb 2018", "July 2019"],
    archived: true,
  },
  {
    title: "Bridgestone Dealer Portal",
    desc: "Updates to a previous site built in AEM.",
    tech: ["AEM"],
    company: "VML",
    client: "Bridgestone",
    date: "2017/03/01",
    dateRange: ["March 2017", "February 2018"],
    archived: true,
  },
  {
    title: "Google I/O Extended Las Vegas",
    img: "/assets/images/google-io-extended.png",
    desc: "Landing page for the Google I/O Extended event in Las Vegas.",
    source: "https://github.com/nathanjessen/ioextendedlv",
    url: "https://nathanjessen.github.io/ioextendedlv/",
    tech: ["Jekyll", "JavaScript"],
    company: "Freelance",
    date: "2017/04/10",
    archived: true,
  },
  {
    title: "Sprint",
    desc: "Complete website redesign including marketplace, shopping cart, and customer support.",
    tech: ["AEM", "AngularJS", "Sass", "Gulp", "Sketch"],
    company: "VML",
    client: "Sprint",
    date: "2015/01/07",
    dateRange: ["Jan 2015", "March 2017"],
    archived: true,
  },
  {
    title: "JG Wentworth",
    desc: "Development of new page layouts and content banners.",
    tech: ["HTML", "CSS"],
    company: "VML",
    client: "JG Wentworth",
    date: "2014/11/01",
    dateRange: ["Nov 2014", "Jan 2015"],
    archived: true,
  },
  {
    title: "Mastercard",
    desc: "Development of informational banners and page heros.",
    tech: ["HTML", "CSS"],
    company: "VML",
    client: "Mastercard",
    date: "2014/09/01",
    dateRange: ["Sept 2014", "Oct 2014"],
    archived: true,
  },
  {
    title: "PepsiCo Careers",
    desc: "Fixed bugs and created new layout components for an existing careers portal.",
    url: "https://www.pepsicojobs.com/main/",
    tech: ["HTML", "CSS"],
    company: "VML",
    client: "PepsiCo",
    date: "2014/08/01",
    dateRange: ["Aug 2014", "Sept 2014"],
    archived: true,
  },
  {
    title: "Efficacy",
    desc: "Promotional landing page for the Sweat It. Get It. ad campaign.",
    tech: ["Jade", "Stylus", "Backbone", "Grunt"],
    company: "VML",
    client: "Gatorade",
    date: "2014/07/30",
    archived: true,
  },
  {
    title: "League of Captains",
    desc: "App with a comic book explorer interface for exploring the information of a marketing campaign.",
    tech: ["Jade", "Stylus", "Backbone", "Grunt"],
    company: "VML",
    client: "Gatorade",
    date: "2014/07/21",
    dateRange: ["June 2014", "July 2014"],
    archived: true,
  },
  {
    title: "Nonstop Love",
    desc: "Landing page for a series of flight discount promotions.",
    tech: ["Assemble", "Sass", "Grunt"],
    company: "VML",
    client: "Southwest Airlines",
    date: "2014/06/14",
    archived: true,
  },
  {
    title: "UltraDuramune",
    desc: "Created a CSS theme for an AEM website.",
    tech: ["AEM", "Handlebars", "Sass", "Grunt"],
    company: "VML",
    client: "Boehringer Ingelheim",
    date: "2014/05/02",
    archived: true,
  },
  {
    title: "Edward Jones Careers",
    desc: "Developed the initial prototype for a careers portal.",
    url: "https://careers.edwardjones.com/",
    tech: ["HTML", "CSS", "JavaScript"],
    company: "VML",
    client: "Edward Jones",
    date: "2014/05/01",
    dateRange: ["March 2014", "May 2014"],
    archived: true,
  },
  {
    title: "Taxonomy",
    desc: "Internal informational website built in AEM.",
    tech: ["AEM", "CSS"],
    company: "VML",
    client: "American Century Investments",
    date: "2014/02/01",
    archived: true,
  },
  {
    title: "Dollars and Sense",
    desc: "Landing page for a new veterinary product.",
    tech: ["HTML5", "Grunt", "Sass"],
    company: "VML",
    client: "Boehringer Ingelheim",
    date: "2014/02/12",
    dateRange: ["Dec 2013", "Feb 2014"],
    archived: true,
  },
  {
    title: "COO / Dealer Portal",
    desc: "Internal portals for Bridgestone managers and product dealers.",
    tech: ["AEM", "LESS", "JavaScript"],
    company: "VML",
    client: "Bridgestone & Firestone",
    date: "2014/01/01",
    dateRange: ["Jan 2014", "Feb 2014"],
    archived: true,
  },
  {
    title: "GCR/TDS Tires & Service",
    desc: "Developed AEM components for a custom map with search for locating nearby stores.",
    url: "http://www.gcrtires.com",
    tech: ["AEM", "Handlebars", "LESS", "JavaScript"],
    company: "VML",
    client: "Bridgestone & Firestone",
    date: "2013/12/01",
    dateRange: ["Dec 2013", "Jan 2014"],
    archived: true,
  },

  {
    title: "Have We Seen Your Cat Lately?",
    desc: "Created a CSS theme for an AEM website.",
    tech: ["AEM", "CSS", "Gulp", "Photoshop"],
    company: "VML",
    client: "Boehringer Ingelheim",
    date: "2013/11/10",
    archived: true,
  },
  {
    title: "Target Date",
    desc: "Parallax website discussing a new program and its benefits.",
    tech: ["AEM", "CSS", "JavaScript", "Photoshop"],
    company: "VML",
    client: "American Century Investments",
    date: "2013/05/01",
    dateRange: ["May 2013", "Sep 2013"],
    archived: true,
  },
  {
    title: "ProZinc",
    desc: "Created a CSS theme for an AEM website.",
    tech: ["AEM", "Handlebars", "Sass", "Photoshop"],
    company: "VML",
    client: "Boehringer Ingelheim",
    date: "2013/04/11",
    dateRange: ["Apr 2013", "May 2013"],
    archived: true,
  },
  {
    title: "Promotional Landing Page",
    desc: "Built a landing page for a marketing campaign.",
    tech: ["HTML", "CSS", "Photoshop"],
    company: "VML",
    client: "Schrader",
    date: "2013/04/01",
    archived: true,
  },
  {
    title: "Duramune Lepto",
    desc: "Created a custom video player for informational videos managed in AEM.",
    tech: ["AEM", "JavaScript", "Bootstrap"],
    company: "VML",
    client: "Boehringer Ingelheim",
    date: "2013/03/20",
    archived: true,
  },
  {
    title: "Rosedale Development Association",
    desc: "Moved a community organization website into WordPress with a child theme at a Coders 4 Charities event.",
    url: "https://rosedale.org/",
    tech: ["WordPress", "CSS"],
    company: "Volunteer",
    client: "Rosedale Development Association",
    date: "2013/03/14",
    archived: true,
  },
  {
    title: "CardioDVM",
    desc: "CSS updates and maintenance for an existing AEM website.",
    tech: ["AEM", "CSS"],
    company: "VML",
    client: "Boehringer Ingelheim",
    date: "2013/03/01",
    archived: true,
  },
  {
    title: "Email Templates",
    desc: "Built email templates used in a marketing campaign for tax preparation services and discounts.",
    tech: ["HTML", "CSS"],
    company: "VML",
    client: "H&R Block",
    date: "2013/01/01",
    dateRange: ["Jan 2013", "Mar 2013"],
    archived: true,
  },
  {
    title: "eVent Fabrics",
    desc: "Developed a WordPress child theme for an apparel company.",
    // url: "http://eventfabrics.com",
    tech: ["WordPress", "Photoshop"],
    company: "VML",
    client: "GE",
    date: "2013/01/15",
    dateRange: ["Dec 2012", "Jan 2013"],
    archived: true,
  },
  {
    title: "ClearCurrent Pro",
    desc: "HTML landing page with a custom YouTube video player.",
    // url: "http://www.clearcurrentpro.com"
    tech: ["HTML", "CSS", "JavaScript", "Photoshop"],
    company: "VML",
    client: "GE",
    date: "2012/11/15",
    archived: true,
  },
  {
    title: "Pexion - Epilepsy in Dogs",
    desc: "Responsive redesign of an AEM website.",
    // url: "https://www.pexion.co.uk/"
    tech: ["AEM", "CSS", "Photoshop"],
    company: "VML",
    client: "Boehringer Ingelheim",
    date: "2012/10/01",
    dateRange: ["Oct 2012", "Nov 2012"],
    archived: true,
  },
  {
    title: "Purefil<sup>TM</sup> Technology",
    desc: "Created a responsive CSS theme for an AEM website.",
    // url: "http://www.bivipurefil.com",
    tech: ["AEM", "CSS", "Photoshop"],
    company: "VML",
    client: "Boehringer Ingelheim",
    date: "2012/09/21",
    dateRange: ["Sept 2012", "Oct 2012"],
    archived: true,
  },

  {
    title: "Email Templates",
    desc: "Built email templates for an email marketing campaign.",
    tech: ["HTML", "CSS"],
    company: "VML",
    client: "GE",
    date: "2012/09/01",
    dateRange: ["Sept 2012"],
    archived: true,
  },
  {
    title: "LymeInfo",
    desc: "Updated the CSS and content for an AEM website.",
    // url: "http://www.lymeinfo.com"
    tech: ["AEM", "CSS"],
    company: "VML",
    client: "Boehringer Ingelheim",
    date: "2012/09/01",
    dateRange: ["Sept 2012"],
    archived: true,
  },
  {
    title: "Pioneer Military Loans",
    desc: "Fixed layout bugs and created CSS updates for a WordPress website.",
    url: "https://pioneermilitarycredit.com/military-loans/",
    tech: ["WordPress", "CSS"],
    company: "VML",
    client: "Pioneer Military Credit",
    date: "2012/09/01",
    dateRange: ["Sept 2012"],
    archived: true,
  },
  {
    title: "Heartland Trailways",
    desc: "Setup a WordPress site and created a child theme for a charter bus company.",
    // url: "http://www.heartlandtrailways.com"
    tech: ["WordPress", "PHP", "CSS", "JavaScript"],
    company: "Freelance",
    client: "Heartland Trailways",
    date: "2011/10/07",
    archived: true,
  },
  {
    title: "Knacktive",
    img: "/assets/images/knacktive.png",
    desc: "Developed the inaugural website for our university-led marketing agency and ported into the university CMS.",
    source: "https://github.com/nathanjessen/knacktive",
    url: "https://nathanjessen.github.io/knacktive/",
    tech: ["HTML", "CSS", "jQuery", "Dreamweaver"],
    company: "Northwest Missouri State University",
    client: "Knacktive",
    date: "2011/02/01",
    archived: true,
  },
];
