name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Identify changed files
        run: |
          git ls-files -m --full-name | grep 'src/.*\.(ts|tsx|js|jsx)$' > changed-files.txt
      - name: Run ESLint on changed files
        run: |
          cat changed-files.txt | xargs npx eslint
