name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Identify changed files
        run: git diff --name-only --diff-filter=AM --relative HEAD
        id: changed
        outputs:
          changedFiles: ${{ steps.changed.outputs.files }}
