name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: push

jobs:
  run-my-workflow:
    name: Run my workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Identify changed files
        run: git diff --name-only --diff-filter=AM --relative HEAD
        id: changed
      - name: Print changed files
        run: echo "${{ steps.changed.outputs.files }}"
      - name: Run ESLint on changed files
        run: |
          npx eslint '**/*.{tsx,ts,js,jsx}' ${{ steps.changed.outputs.files }}
