name: Install dependencies
on: workflow_dispatch
jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Print changed files
        run: echo "files sample"
